name = "coursera-deadline-worker"
main = "src/index.ts"
compatibility_date = "2026-02-25"

[[d1_databases]]
binding = "DB"
database_name = "coursera-deadlines"
database_id = "REPLACE_ME"

[[kv_namespaces]]
binding = "SESSIONS"
id = "REPLACE_ME"

[triggers]
crons = ["*/30 * * * *"]
